import type { Agent, ArtifactCheck, DeliveryManifest, Dispute, ExecutionQueueItem, ReputationEvent, SettlementEvent, Skill, Task, TaskResult } from "./types";
import { normalizeArtifactReferences } from "./task-contracts";

export const agentDto = (agent: Agent) => ({
  agent_id: agent.id,
  publisher_wallet: agent.publisherWallet,
  name: agent.name,
  description: agent.description,
  status: agent.status,
  reputation_score: agent.reputationScore,
  success_rate: agent.successRate,
  avg_latency_ms: agent.avgLatencyMs,
  quality_score: agent.qualityScore,
  delegation_success_rate: agent.delegationSuccessRate,
  historical_earnings_lamports: agent.historicalEarningsLamports,
  stake_amount: agent.stakeAmount,
  verified_completion_rate: agent.verifiedCompletionRate,
  on_time_delivery_rate: agent.onTimeDeliveryRate,
  dispute_rate: agent.disputeRate,
  unsafe_artifact_rate: agent.unsafeArtifactRate,
  refund_rate: agent.refundRate,
  total_tasks_completed: agent.totalTasksCompleted,
  total_tasks_failed: agent.totalTasksFailed,
  total_disputes: agent.totalDisputes,
  created_at: agent.createdAt,
  updated_at: agent.updatedAt,
});

export const skillDto = (skill: Skill) => ({
  skill_id: skill.id,
  agent_id: skill.agentId,
  name: skill.name,
  description: skill.description,
  input_schema: skill.inputSchema,
  output_schema: skill.outputSchema,
  base_price_lamports: skill.basePriceLamports,
  estimated_latency_ms: skill.estimatedLatencyMs,
  required_permissions: skill.requiredPermissions,
  created_at: skill.createdAt,
  updated_at: skill.updatedAt,
});

export const taskDto = (task: Task) => ({
  task_id: task.id,
  parent_task_id: task.parentTaskId,
  hirer_agent_id: task.hirerAgentId,
  worker_agent_id: task.workerAgentId,
  skill_id: task.skillId,
  task_payload: task.taskPayload,
  payment_lamports: task.paymentLamports,
  platform_fee_lamports: task.platformFeeLamports,
  runtime_fee_lamports: task.runtimeFeeLamports,
  worker_payout_lamports: task.workerPayoutLamports,
  deadline: task.deadline,
  status: task.status,
  escrow_account: task.escrowAccount,
  escrow_tx_signature: task.escrowTxSignature,
  settlement_tx_signature: task.settlementTxSignature,
  accepted_at: task.acceptedAt,
  submitted_at: task.submittedAt,
  completed_at: task.completedAt,
  acceptance_snapshot_hash: task.acceptanceSnapshotHash,
  delivery_protocol_version: task.deliveryProtocolVersion,
  settlement_mode: task.settlementMode,
  created_at: task.createdAt,
  updated_at: task.updatedAt,
});

export const taskResultDto = (result: TaskResult) => ({
  result_id: result.id,
  task_id: result.taskId,
  worker_agent_id: result.workerAgentId,
  result_payload: result.resultPayload,
  artifacts: result.artifacts,
  artifact_references: normalizeArtifactReferences(result.artifacts),
  quality_score: result.qualityScore,
  submitted_at: result.submittedAt,
});

export const reputationEventDto = (event: ReputationEvent) => ({
  event_id: event.id,
  agent_id: event.agentId,
  task_id: event.taskId,
  success: event.success,
  latency_ms: event.latencyMs,
  quality_score: event.qualityScore,
  review_score: event.reviewScore,
  delegation_success: event.delegationSuccess,
  reputation_delta: event.reputationDelta,
  verification_status: event.verificationStatus,
  reason: event.reason,
  created_at: event.createdAt,
});

export const settlementEventDto = (event: SettlementEvent) => ({
  event_id: event.id,
  task_id: event.taskId,
  event_type: event.eventType,
  amount_lamports: event.amountLamports,
  from_wallet: event.fromWallet,
  to_wallet: event.toWallet,
  tx_signature: event.txSignature,
  failure_reason: event.failureReason,
  confirmation_status: event.confirmationStatus,
  created_at: event.createdAt,
});

export const deliveryManifestDto = (manifest: DeliveryManifest) => ({
  manifest_id: manifest.id,
  task_result_id: manifest.taskResultId,
  task_id: manifest.taskId,
  manifest_version: manifest.manifestVersion,
  public_safe: manifest.publicSafe,
  manifest_payload: manifest.manifestPayload,
  manifest_hash: manifest.manifestHash,
  inputs: manifest.inputs,
  outputs: manifest.outputs,
  verifier_status: manifest.verifierStatus,
  verifier_command: manifest.verifierCommand,
  verifier_expected_output: manifest.verifierExpectedOutput,
  verifier_exit_code: manifest.verifierExitCode,
  verifier_stdout: manifest.verifierStdout,
  verifier_stdout_hash: manifest.verifierStdoutHash,
  verifier_ran_at: manifest.verifierRanAt,
  verification_timeout_ms: manifest.verificationTimeoutMs,
  created_at: manifest.createdAt,
});

export const artifactCheckDto = (check: ArtifactCheck) => ({
  check_id: check.id,
  task_result_id: check.taskResultId,
  task_id: check.taskId,
  artifact_uri: check.artifactUri,
  artifact_hash: check.artifactHash,
  safety_status: check.safetyStatus,
  secret_scan_status: check.secretScanStatus,
  secret_scan_findings: check.secretScanFindings,
  displayable: check.displayable,
  scanned_at: check.scannedAt,
  created_at: check.createdAt,
});

export const disputeDto = (dispute: Dispute) => ({
  dispute_id: dispute.id,
  task_id: dispute.taskId,
  opened_by: dispute.openedBy,
  reason: dispute.reason,
  status: dispute.status,
  evaluator_agent_id: dispute.evaluatorAgentId,
  resolution: dispute.resolution,
  resolution_notes: dispute.resolutionNotes,
  settlement_action: dispute.settlementAction,
  opened_at: dispute.openedAt,
  resolved_at: dispute.resolvedAt,
});

export const executionQueueItemDto = (item: ExecutionQueueItem) => ({
  execution_id: item.id,
  task_id: item.taskId,
  status: item.status,
  attempts: item.attempts,
  max_attempts: item.maxAttempts,
  last_error: item.lastError,
  next_retry_at: item.nextRetryAt,
  started_at: item.startedAt,
  completed_at: item.completedAt,
  timeout_ms: item.timeoutMs,
  runtime_adapter: item.runtimeAdapter,
  created_at: item.createdAt,
});
